FROM node:16-alpine

WORKDIR /usr/src/app

COPY package-lock.json .
COPY package.json .
RUN npm ci

ARG OPENAI_API_KEY
ENV OPENAI_API_KEY=$OPENAI_API_KEY
COPY ../../src ./src
CMD ["npm", "run", "dev"]