name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t liran86/ai_debugger_server:${{ github.sha }} -f src/config/Dockerfile .

      - name: Deploy to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker tag liran86/ai_debugger_server:${{ github.sha }} liran86/ai_debugger_server:latest
          docker push liran86/ai_debugger_server:${{ github.sha }}
          docker push liran86/ai_debugger_server:latest
